% Define os tokens da gramática.
token(void, keyword).
token(char, keyword).
token(int, keyword).
token(main, keyword).
token(if, keyword).
token(else, keyword).
token(while, keyword).
token(return, keyword).
token(break, keyword).
token(true, constant).
token(false, constant).
token("(", lparen).
token(")", rparen).
token("{", lbrace).
token("}", rbrace).
token("[", lbracket).
token("]", rbracket).
token(";", semicolon).
token(",", comma).
token(":", colon).
token("=", assignop).
token("+=", assignop).
token("-=", assignop).
token("*=", assignop).
token("/=", assignop).
token("==", relop).
token("!=", relop).
token("<", relop).
token("<=", relop).
token(">", relop).
token(">=", relop).
token("+", sumop).
token("-", sumop).
token("*", mulop).
token("/", mulop).
token("%", mulop).
token("&&", andop).
token("||", orop).
token("!", notop).

